[package]
name = "regex-test"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "benchmark"
harness = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.5.1"
regex = "1.9.5"
